version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf x
    

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - ADMIN_USERS=postgres,admin
    volumes:
      - ./userlist.txt:/pgbouncer/userlist.txt
      - ./pgbouncer.ini:/pgbouncer/pgbouncer.ini
    depends_on:
      - db
  


  redis:
    image: "redis:alpine"


  
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A bono_bar.django worker --loglevel=info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A bono_bar.django beat --loglevel=info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db

volumes:
  dbdata:
  static_volume:
  media_volume:
